import { Job } from "./jobs.types";

export const jobsMockData: Job[] = [
  {
    id: "1",
    title: "Software Engineer",
    description: "Develop and maintain applications.",
    salaryMin: 1000,
    salaryMax: 2000,
    location: "Remote",
    company: "Tech Corp",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["JavaScript", "React", "Node.js"],
    type: "full-time",
    category: "IT",
  },
  {
    id: "2",
    title: "Data Analyst",
    description: "Analyze business data to generate insights.",
    salaryMin: 1500,
    salaryMax: 2500,
    location: "New York",
    company: "Data Inc",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["SQL", "Python", "Tableau"],
    type: "full-time",
    category: "Data Science",
  },
  {
    id: "3",
    title: "Product Manager",
    description: "Oversee product development lifecycle.",
    salaryMin: 3000,
    salaryMax: 5000,
    location: "San Francisco",
    company: "Innovate LLC",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Agile", "Scrum", "Leadership"],
    type: "full-time",
    category: "Management",
  },
  {
    id: "4",
    title: "UX Designer",
    description: "Design user interfaces for web and mobile apps.",
    salaryMin: 2000,
    salaryMax: 3500,
    location: "London",
    company: "Design Studio",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Figma", "Sketch", "Wireframing"],
    type: "contract",
    category: "Design",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    description: "Manage cloud infrastructure and CI/CD pipelines.",
    salaryMin: 2500,
    salaryMax: 4000,
    location: "Berlin",
    company: "Cloud Solutions",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["AWS", "Docker", "Kubernetes"],
    type: "full-time",
    category: "IT",
  },
  {
    id: "6",
    title: "Marketing Specialist",
    description: "Develop marketing strategies and campaigns.",
    salaryMin: 1800,
    salaryMax: 2800,
    location: "Sydney",
    company: "Marketing Hub",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["SEO", "Content", "Social Media"],
    type: "part-time",
    category: "Marketing",
  },
  {
    id: "7",
    title: "Finance Manager",
    description: "Manage financial planning and analysis.",
    salaryMin: 4000,
    salaryMax: 6000,
    location: "Toronto",
    company: "Finance Corp",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Accounting", "Budgeting", "Forecasting"],
    type: "full-time",
    category: "Finance",
  },
  {
    id: "8",
    title: "Customer Support Specialist",
    description: "Provide support to customers via chat and email.",
    salaryMin: 1200,
    salaryMax: 1800,
    location: "Remote",
    company: "HelpDesk",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Customer Service", "Zendesk", "CRM"],
    type: "contract",
    category: "Support",
  },
  {
    id: "9",
    title: "Graphic Designer",
    description: "Create visual content for digital platforms.",
    salaryMin: 2200,
    salaryMax: 3200,
    location: "Paris",
    company: "Creative Designs",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Photoshop", "Illustrator", "Creativity"],
    type: "full-time",
    category: "Design",
  },
  {
    id: "10",
    title: "HR Coordinator",
    description: "Support HR processes and employee engagement.",
    salaryMin: 1600,
    salaryMax: 2600,
    location: "Singapore",
    company: "HR Solutions",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Recruitment", "Payroll", "Onboarding"],
    type: "full-time",
    category: "Human Resources",
  },
  {
    id: "11",
    title: "AI Researcher",
    description: "Conduct research in artificial intelligence.",
    salaryMin: 5000,
    salaryMax: 7000,
    location: "Boston",
    company: "AI Labs",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Machine Learning", "Deep Learning", "Python"],
    type: "full-time",
    category: "Research",
  },
  {
    id: "12",
    title: "Sales Executive",
    description: "Drive sales and build client relationships.",
    salaryMin: 2000,
    salaryMax: 3500,
    location: "Dubai",
    company: "Sales Pros",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Sales", "CRM", "Negotiation"],
    type: "full-time",
    category: "Sales",
  },
  {
    id: "13",
    title: "Mobile Developer",
    description: "Develop mobile applications for Android and iOS.",
    salaryMin: 2800,
    salaryMax: 4500,
    location: "Tokyo",
    company: "App Makers",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Flutter", "Kotlin", "Swift"],
    type: "full-time",
    category: "IT",
  },
  {
    id: "14",
    title: "Content Writer",
    description: "Create and edit content for websites and blogs.",
    salaryMin: 1300,
    salaryMax: 2200,
    location: "Remote",
    company: "Content Creators",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Writing", "SEO", "Editing"],
    type: "part-time",
    category: "Content",
  },
  {
    id: "15",
    title: "Systems Administrator",
    description: "Maintain and support IT infrastructure.",
    salaryMin: 2700,
    salaryMax: 4200,
    location: "Amsterdam",
    company: "IT Services",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tags: ["Linux", "Networking", "Security"],
    type: "full-time",
    category: "IT",
  },
];
